[build]
  command = "npm install && npm run build"

[build.environment]
  PORT = "4829"

[build.publish]
  path = "server"

[build.functions]
  directory = "serverless"

[redirects]
  from = "/rps/*"
  to = "/.netlify/functions/rps/:splat"
  status = 200
